/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq;


import guru.springframework.jooq.tables.Category;
import guru.springframework.jooq.tables.Ingredient;
import guru.springframework.jooq.tables.Notes;
import guru.springframework.jooq.tables.Recipe;
import guru.springframework.jooq.tables.RecipeCategory;
import guru.springframework.jooq.tables.UnitOfMeasure;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>CATEGORY</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>INGREDIENT</code>.
     */
    public final Ingredient INGREDIENT = Ingredient.INGREDIENT;

    /**
     * The table <code>NOTES</code>.
     */
    public final Notes NOTES = Notes.NOTES;

    /**
     * The table <code>RECIPE</code>.
     */
    public final Recipe RECIPE = Recipe.RECIPE;

    /**
     * The table <code>RECIPE_CATEGORY</code>.
     */
    public final RecipeCategory RECIPE_CATEGORY = RecipeCategory.RECIPE_CATEGORY;

    /**
     * The table <code>UNIT_OF_MEASURE</code>.
     */
    public final UnitOfMeasure UNIT_OF_MEASURE = UnitOfMeasure.UNIT_OF_MEASURE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Ingredient.INGREDIENT,
            Notes.NOTES,
            Recipe.RECIPE,
            RecipeCategory.RECIPE_CATEGORY,
            UnitOfMeasure.UNIT_OF_MEASURE);
    }
}
