/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq;


import guru.springframework.jooq.tables.Category;
import guru.springframework.jooq.tables.Ingredient;
import guru.springframework.jooq.tables.Notes;
import guru.springframework.jooq.tables.Recipe;
import guru.springframework.jooq.tables.RecipeCategory;
import guru.springframework.jooq.tables.UnitOfMeasure;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CATEGORY</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>INGREDIENT</code>.
     */
    public static final Ingredient INGREDIENT = Ingredient.INGREDIENT;

    /**
     * The table <code>NOTES</code>.
     */
    public static final Notes NOTES = Notes.NOTES;

    /**
     * The table <code>RECIPE</code>.
     */
    public static final Recipe RECIPE = Recipe.RECIPE;

    /**
     * The table <code>RECIPE_CATEGORY</code>.
     */
    public static final RecipeCategory RECIPE_CATEGORY = RecipeCategory.RECIPE_CATEGORY;

    /**
     * The table <code>UNIT_OF_MEASURE</code>.
     */
    public static final UnitOfMeasure UNIT_OF_MEASURE = UnitOfMeasure.UNIT_OF_MEASURE;
}
