/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq.tables;


import guru.springframework.jooq.SpringGuruRecipe;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ingredient extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>spring_guru_recipe.ingredient</code>
     */
    public static final Ingredient INGREDIENT = new Ingredient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>spring_guru_recipe.ingredient.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>spring_guru_recipe.ingredient.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>spring_guru_recipe.ingredient.amount</code>.
     */
    public final TableField<Record, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.DECIMAL(12, 2), this, "");

    /**
     * The column <code>spring_guru_recipe.ingredient.recipe_id</code>.
     */
    public final TableField<Record, Long> RECIPE_ID = createField(DSL.name("recipe_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>spring_guru_recipe.ingredient.uom_id</code>.
     */
    public final TableField<Record, Long> UOM_ID = createField(DSL.name("uom_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Ingredient(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Ingredient(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>spring_guru_recipe.ingredient</code> table reference
     */
    public Ingredient(String alias) {
        this(DSL.name(alias), INGREDIENT);
    }

    /**
     * Create an aliased <code>spring_guru_recipe.ingredient</code> table reference
     */
    public Ingredient(Name alias) {
        this(alias, INGREDIENT);
    }

    /**
     * Create a <code>spring_guru_recipe.ingredient</code> table reference
     */
    public Ingredient() {
        this(DSL.name("ingredient"), null);
    }

    @Override
    public Schema getSchema() {
        return SpringGuruRecipe.SPRING_GURU_RECIPE;
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(Ingredient.INGREDIENT, DSL.name("KEY_ingredient_PRIMARY"), new TableField[] { Ingredient.INGREDIENT.ID }, true);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(Ingredient.INGREDIENT, DSL.name("KEY_ingredient_PRIMARY"), new TableField[] { Ingredient.INGREDIENT.ID }, true)
        );
    }

    @Override
    public Ingredient as(String alias) {
        return new Ingredient(DSL.name(alias), this);
    }

    @Override
    public Ingredient as(Name alias) {
        return new Ingredient(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredient rename(String name) {
        return new Ingredient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingredient rename(Name name) {
        return new Ingredient(name, null);
    }
}
