/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq.tables;


import guru.springframework.jooq.DefaultSchema;
import guru.springframework.jooq.Keys;
import guru.springframework.jooq.tables.records.RecipeCategoryRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeCategory extends TableImpl<RecipeCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>RECIPE_CATEGORY</code>
     */
    public static final RecipeCategory RECIPE_CATEGORY = new RecipeCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecipeCategoryRecord> getRecordType() {
        return RecipeCategoryRecord.class;
    }

    /**
     * The column <code>RECIPE_CATEGORY.RECIPE_ID</code>.
     */
    public final TableField<RecipeCategoryRecord, Long> RECIPE_ID = createField(DSL.name("RECIPE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>RECIPE_CATEGORY.CATEGORY_ID</code>.
     */
    public final TableField<RecipeCategoryRecord, Long> CATEGORY_ID = createField(DSL.name("CATEGORY_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private RecipeCategory(Name alias, Table<RecipeCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private RecipeCategory(Name alias, Table<RecipeCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>RECIPE_CATEGORY</code> table reference
     */
    public RecipeCategory(String alias) {
        this(DSL.name(alias), RECIPE_CATEGORY);
    }

    /**
     * Create an aliased <code>RECIPE_CATEGORY</code> table reference
     */
    public RecipeCategory(Name alias) {
        this(alias, RECIPE_CATEGORY);
    }

    /**
     * Create a <code>RECIPE_CATEGORY</code> table reference
     */
    public RecipeCategory() {
        this(DSL.name("RECIPE_CATEGORY"), null);
    }

    public <O extends Record> RecipeCategory(Table<O> child, ForeignKey<O, RecipeCategoryRecord> key) {
        super(child, key, RECIPE_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<RecipeCategoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    public List<UniqueKey<RecipeCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<RecipeCategoryRecord>>asList(Keys.CONSTRAINT_D);
    }

    @Override
    public List<ForeignKey<RecipeCategoryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RecipeCategoryRecord, ?>>asList(Keys.FKCQLQNVFYARHIEEWFEAYK3V25V, Keys.FKQSI87I8D4QQDEHLV2EIWVPWB);
    }

    public Recipe recipe() {
        return new Recipe(this, Keys.FKCQLQNVFYARHIEEWFEAYK3V25V);
    }

    public Category category() {
        return new Category(this, Keys.FKQSI87I8D4QQDEHLV2EIWVPWB);
    }

    @Override
    public RecipeCategory as(String alias) {
        return new RecipeCategory(DSL.name(alias), this);
    }

    @Override
    public RecipeCategory as(Name alias) {
        return new RecipeCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipeCategory rename(String name) {
        return new RecipeCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipeCategory rename(Name name) {
        return new RecipeCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
