/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq.tables;


import guru.springframework.jooq.DefaultSchema;
import guru.springframework.jooq.Keys;
import guru.springframework.jooq.tables.records.RecipeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recipe extends TableImpl<RecipeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>RECIPE</code>
     */
    public static final Recipe RECIPE = new Recipe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecipeRecord> getRecordType() {
        return RecipeRecord.class;
    }

    /**
     * The column <code>RECIPE.ID</code>.
     */
    public final TableField<RecipeRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>RECIPE.COOK_TIME</code>.
     */
    public final TableField<RecipeRecord, Integer> COOK_TIME = createField(DSL.name("COOK_TIME"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>RECIPE.DESCRIPTION</code>.
     */
    public final TableField<RecipeRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>RECIPE.DIFFICULTY</code>.
     */
    public final TableField<RecipeRecord, String> DIFFICULTY = createField(DSL.name("DIFFICULTY"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>RECIPE.DIRECTIONS</code>.
     */
    public final TableField<RecipeRecord, String> DIRECTIONS = createField(DSL.name("DIRECTIONS"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>RECIPE.IMAGE</code>.
     */
    public final TableField<RecipeRecord, byte[]> IMAGE = createField(DSL.name("IMAGE"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>RECIPE.PREP_TIME</code>.
     */
    public final TableField<RecipeRecord, Integer> PREP_TIME = createField(DSL.name("PREP_TIME"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>RECIPE.SERVINGS</code>.
     */
    public final TableField<RecipeRecord, Integer> SERVINGS = createField(DSL.name("SERVINGS"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>RECIPE.SOURCE</code>.
     */
    public final TableField<RecipeRecord, String> SOURCE = createField(DSL.name("SOURCE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>RECIPE.URL</code>.
     */
    public final TableField<RecipeRecord, String> URL = createField(DSL.name("URL"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>RECIPE.NOTES_ID</code>.
     */
    public final TableField<RecipeRecord, Long> NOTES_ID = createField(DSL.name("NOTES_ID"), SQLDataType.BIGINT, this, "");

    private Recipe(Name alias, Table<RecipeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Recipe(Name alias, Table<RecipeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>RECIPE</code> table reference
     */
    public Recipe(String alias) {
        this(DSL.name(alias), RECIPE);
    }

    /**
     * Create an aliased <code>RECIPE</code> table reference
     */
    public Recipe(Name alias) {
        this(alias, RECIPE);
    }

    /**
     * Create a <code>RECIPE</code> table reference
     */
    public Recipe() {
        this(DSL.name("RECIPE"), null);
    }

    public <O extends Record> Recipe(Table<O> child, ForeignKey<O, RecipeRecord> key) {
        super(child, key, RECIPE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<RecipeRecord, Long> getIdentity() {
        return (Identity<RecipeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RecipeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    public List<UniqueKey<RecipeRecord>> getKeys() {
        return Arrays.<UniqueKey<RecipeRecord>>asList(Keys.CONSTRAINT_8);
    }

    @Override
    public List<ForeignKey<RecipeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RecipeRecord, ?>>asList(Keys.FK37AL6KCBDASGFNUT9XOKKTIE9);
    }

    public Notes notes() {
        return new Notes(this, Keys.FK37AL6KCBDASGFNUT9XOKKTIE9);
    }

    @Override
    public Recipe as(String alias) {
        return new Recipe(DSL.name(alias), this);
    }

    @Override
    public Recipe as(Name alias) {
        return new Recipe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Recipe rename(String name) {
        return new Recipe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Recipe rename(Name name) {
        return new Recipe(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Integer, String, String, String, byte[], Integer, Integer, String, String, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
