/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq.tables;


import guru.springframework.jooq.SpringGuruRecipe;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recipe extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>spring_guru_recipe.recipe</code>
     */
    public static final Recipe RECIPE = new Recipe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>spring_guru_recipe.recipe.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.cook_time</code>.
     */
    public final TableField<Record, Long> COOK_TIME = createField(DSL.name("cook_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.prep_time</code>.
     */
    public final TableField<Record, Long> PREP_TIME = createField(DSL.name("prep_time"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.servings</code>.
     */
    public final TableField<Record, Long> SERVINGS = createField(DSL.name("servings"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.description</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.url</code>.
     */
    public final TableField<Record, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.source</code>.
     */
    public final TableField<Record, String> SOURCE = createField(DSL.name("source"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.difficulty</code>.
     */
    public final TableField<Record, String> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.directions</code>.
     */
    public final TableField<Record, String> DIRECTIONS = createField(DSL.name("directions"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.image</code>.
     */
    public final TableField<Record, byte[]> IMAGE = createField(DSL.name("image"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>spring_guru_recipe.recipe.notes_id</code>.
     */
    public final TableField<Record, Long> NOTES_ID = createField(DSL.name("notes_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Recipe(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Recipe(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>spring_guru_recipe.recipe</code> table reference
     */
    public Recipe(String alias) {
        this(DSL.name(alias), RECIPE);
    }

    /**
     * Create an aliased <code>spring_guru_recipe.recipe</code> table reference
     */
    public Recipe(Name alias) {
        this(alias, RECIPE);
    }

    /**
     * Create a <code>spring_guru_recipe.recipe</code> table reference
     */
    public Recipe() {
        this(DSL.name("recipe"), null);
    }

    @Override
    public Schema getSchema() {
        return SpringGuruRecipe.SPRING_GURU_RECIPE;
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(Recipe.RECIPE, DSL.name("KEY_recipe_PRIMARY"), new TableField[] { Recipe.RECIPE.ID }, true);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(Recipe.RECIPE, DSL.name("KEY_recipe_PRIMARY"), new TableField[] { Recipe.RECIPE.ID }, true)
        );
    }

    @Override
    public Recipe as(String alias) {
        return new Recipe(DSL.name(alias), this);
    }

    @Override
    public Recipe as(Name alias) {
        return new Recipe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Recipe rename(String name) {
        return new Recipe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Recipe rename(Name name) {
        return new Recipe(name, null);
    }
}
