/*
 * This file is generated by jOOQ.
 */
package guru.springframework.jooq.tables.records;


import guru.springframework.jooq.tables.Notes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesRecord extends UpdatableRecordImpl<NotesRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>NOTES.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>NOTES.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>NOTES.RECIPE_NOTES</code>.
     */
    public void setRecipeNotes(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>NOTES.RECIPE_NOTES</code>.
     */
    public String getRecipeNotes() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notes.NOTES.ID;
    }

    @Override
    public Field<String> field2() {
        return Notes.NOTES.RECIPE_NOTES;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRecipeNotes();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRecipeNotes();
    }

    @Override
    public NotesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotesRecord value2(String value) {
        setRecipeNotes(value);
        return this;
    }

    @Override
    public NotesRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotesRecord
     */
    public NotesRecord() {
        super(Notes.NOTES);
    }

    /**
     * Create a detached, initialised NotesRecord
     */
    public NotesRecord(Long id, String recipeNotes) {
        super(Notes.NOTES);

        setId(id);
        setRecipeNotes(recipeNotes);
    }
}
