/*
 * This file is generated by jOOQ.
 */
package com.recipe.application.jooq.tables;


import com.recipe.application.jooq.DefaultSchema;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitOfMeasure extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>UNIT_OF_MEASURE</code>
     */
    public static final UnitOfMeasure UNIT_OF_MEASURE = new UnitOfMeasure();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>UNIT_OF_MEASURE.ID</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>UNIT_OF_MEASURE.DESCRIPTION</code>.
     */
    public final TableField<Record, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(255), this, "");

    private UnitOfMeasure(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private UnitOfMeasure(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>UNIT_OF_MEASURE</code> table reference
     */
    public UnitOfMeasure(String alias) {
        this(DSL.name(alias), UNIT_OF_MEASURE);
    }

    /**
     * Create an aliased <code>UNIT_OF_MEASURE</code> table reference
     */
    public UnitOfMeasure(Name alias) {
        this(alias, UNIT_OF_MEASURE);
    }

    /**
     * Create a <code>UNIT_OF_MEASURE</code> table reference
     */
    public UnitOfMeasure() {
        this(DSL.name("UNIT_OF_MEASURE"), null);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<Record, Long> getIdentity() {
        return (Identity<Record, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(UnitOfMeasure.UNIT_OF_MEASURE, DSL.name("CONSTRAINT_4E"), new TableField[] { UnitOfMeasure.UNIT_OF_MEASURE.ID }, true);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(UnitOfMeasure.UNIT_OF_MEASURE, DSL.name("CONSTRAINT_4E"), new TableField[] { UnitOfMeasure.UNIT_OF_MEASURE.ID }, true)
        );
    }

    @Override
    public UnitOfMeasure as(String alias) {
        return new UnitOfMeasure(DSL.name(alias), this);
    }

    @Override
    public UnitOfMeasure as(Name alias) {
        return new UnitOfMeasure(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UnitOfMeasure rename(String name) {
        return new UnitOfMeasure(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UnitOfMeasure rename(Name name) {
        return new UnitOfMeasure(name, null);
    }
}
