/*
 * This file is generated by jOOQ.
 */
package com.recipe.application.jooq;


import com.recipe.application.jooq.tables.Category;
import com.recipe.application.jooq.tables.Ingredient;
import com.recipe.application.jooq.tables.Notes;
import com.recipe.application.jooq.tables.Recipe;
import com.recipe.application.jooq.tables.RecipeCategory;
import com.recipe.application.jooq.tables.UnitOfMeasure;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            Ingredient.INGREDIENT,
            Notes.NOTES,
            Recipe.RECIPE,
            RecipeCategory.RECIPE_CATEGORY,
            UnitOfMeasure.UNIT_OF_MEASURE);
    }
}
